baseURL = 'https://webtest.ealingwoodcraft.org.uk/'
languageCode = 'en-gb'
title = 'My New Hugo Site'

[deployment]
[[deployment.targets]]
# An arbitrary name for this target.
name = "production"

URL = "s3://webtest.ealingwoodcraft.org.uk?region=eu-west-2&prefix=public/"

