name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-role
          role-session-name: terraform-session
          aws-region: eu-west-2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        extended: true
        hugo-version: '0.136.0'

    - name: Build Hugo site
      run: hugo

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: ./terraform



    #- name: Deploy Hugo site
    #  run: hugo deploy
    #  working-directory: ./ealingwoodcraft