name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-role
          role-session-name: terraform-session
          aws-region: eu-west-2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init
      dir: ./terraform

    - name: Apply Terraform
      run: terraform apply -auto-approve -var "deployment_user_arn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-role"
      dir: ./terraform

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2

    - name: Build Hugo site
      run: hugo
      dir: ./ealingwoodcraft